run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 12m

linters:
  enable:
    - bodyclose
    - durationcheck
    - errorlint
    - gofmt
    - goimports
    - revive
    - gosec
    - misspell
    - nakedret
    - nilerr
    - unconvert
    - unparam
    - intrange
    - whitespace
    - gocritic
    - wastedassign
    - nolintlint

linters-settings:
  govet:
    enable:
      - nilness
      - sortslice
      - unusedwrite
  revive:
    # minimal confidence for issues, default is 0.8
    min-confidence: 0.0
