name: Nightly Build
on:
  schedule:
    # Random minute number to avoid GH scheduler stampede
    - cron: '37 21 * * *'
  workflow_dispatch: {}
env:
  GO_VERSION: 1.22.1

jobs:
  build-and-publish-images:
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Install regctl
        uses: regclient/actions/regctl-installer@main
      - name: Build image
        run: make docker-build
      - name: Log in to GHCR
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push images
        run: ./.github/workflows/scripts/push-images.sh nightly
